name: EasyWarp-Reloaded
version: '${project.version}'
main: krisapps.easywarpreloaded.EasyWarpReloaded
api-version: '1.19'

commands:
  warp:
    description: "Warps the player to a warp."
    usage: "/warp <warp>"
    permission: easywarp.warp

  warpman:
    description: "Manages warps' settings."
    usage: "/warpman <create|edit|delete|list|view> <params...>"
    permission: easywarp.create
    aliases:
      - easywarp
      - warpmanager

  back:
    description: "Attempts to return the player to whence they teleported from."
    usage: "/back"
    permission: easywarp.warp

  invite:
    description: "Creates and sends an invite to a private warp to the specified player."
    usage: "/invite <player> <warp> <uses>"
    permission: easywarp.warp
    aliases:
      - invitetowarp
      - inviteplayer

  setlanguage:
    description: "Changes the language of the plugin."
    usage: "/setlanguage <langCode>"
    aliases:
      - lang
      - setlang

  invites:
    description: "Shows invites for a warp."
    usage: "/invites <warp>"
    permission: easywarp.create
    aliases:
      - viewinvites
      - listinvites

permissions:
  easywarp.warp:
    description: "The default permission, allows warping"
    default: true
  easywarp.useprivatewarps:
    description: "Allows a player to create, edit, delete and warp to private warps."
    default: true
  easywarp.invite:
    description: "Allows a player to invite others to a warp."
    default: false
  easywarp.manage:
    description: "Allows a player to manage all existing warps, including those belonging to other players."
    default: op